---
include:
  - board: eyelash_sofle_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_sofle_right
    shield: nice_view_custom
  - board: eyelash_sofle_left
    shield: settings_reset
    snippet: studio-rpc-usb-uart
